language: php

php:
  - 7.3
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --exclude-group integration; fi'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
